name: app_update_apk_installer
description: "A new Flutter plugin project."
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  app_update:
    path: ../.. # TODO поменять на путь с Pub-а
  dio: ^5.7.0
  path_provider: ^2.1.5
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  pub_semver: ^2.2.0

  project_kit:
    git:
      url: https://github.com/StarProxima/dev_kit
      ref: develop
      path: unpublished/project_kit

flutter:
  plugin:
    platforms:
      android:
        package: com.blancvpn.app_update_apk_installer
        pluginClass: AppUpdateApkInstallerPlugin